alexie/urls.py
from django.conf.urls import url

from . import views

app_name = "alexie"

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # For every model

    # create
    # saveCreate  # avoid "confirm form resubmission" on browser reload
    # read
    # update
    # saveUpdate
    # confirmDelete
    # delete
    
    # AccountType
    url(r'^accountType/create$', views.accountTypeCreate, name="accountTypeCreate"),
    url(r'^accountType/saveCreate$', views.accountTypeSaveCreate, name="accountTypeSaveCreate"),
    url(r'^accountType/read/(?P<pk>[0-9]+)$', views.accountTypeRead, name="accountTypeRead"),
    url(r'^accountType/update/(?P<pk>[0-9]+)$', views.accountTypeUpdate, name="accountTypeUpdate"),
    url(r'^accountType/saveUpdate/(?P<pk>[0-9]+)$', views.accountTypeSaveUpdate, name="accountTypeSaveUpdate"),
    url(r'^accountType/confirmDelete/(?P<pk>[0-9]+)$', views.accountTypeConfirmDelete, name="accountTypeConfirmDelete"),
    url(r'^accountType/delete/(?P<pk>[0-9]+)$', views.accountTypeDelete, name="accountTypeDelete"),

    # Account
    url(r'^account/create$', views.accountCreate, name="accountCreate"),
    url(r'^account/saveCreate$', views.accountSaveCreate, name="accountSaveCreate"),
    url(r'^account/read/(?P<pk>[0-9]+)$', views.accountRead, name="accountRead"),
    url(r'^account/update/(?P<pk>[0-9]+)$', views.accountUpdate, name="accountUpdate"),
    url(r'^account/saveUpdate/(?P<pk>[0-9]+)$', views.accountSaveUpdate, name="accountSaveUpdate"),
    url(r'^account/confirmDelete/(?P<pk>[0-9]+)$', views.accountConfirmDelete, name="accountConfirmDelete"),
    url(r'^account/delete/(?P<pk>[0-9]+)$', views.accountDelete, name="accountDelete"),

    # Transaction
    url(r'^transaction/create$', views.transactionCreate, name="transactionCreate"),
    url(r'^transaction/saveCreate$', views.transactionSaveCreate, name="transactionSaveCreate"),
    url(r'^transaction/read/(?P<pk>[0-9]+)$', views.transactionRead, name="transactionRead"),
    url(r'^transaction/update/(?P<pk>[0-9]+)$', views.transactionUpdate, name="transactionUpdate"),
    url(r'^transaction/saveUpdate/(?P<pk>[0-9]+)$', views.transactionSaveUpdate, name="transactionSaveUpdate"),
    url(r'^transaction/confirmDelete/(?P<pk>[0-9]+)$', views.transactionConfirmDelete, name="transactionConfirmDelete"),
    url(r'^transaction/delete/(?P<pk>[0-9]+)$', views.transactionDelete, name="transactionDelete"),
]

benny/urls.py
from django.conf.urls import url

from . import views

app_name = "benny"

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # For every model

    # create
    # saveCreate  # avoid "confirm form resubmission" on browser reload
    # read
    # update
    # saveUpdate
    # confirmDelete
    # delete
    
    # AccountType

    url(r'^accountType/create$', views.accountTypeCreate, name="accountTypeCreate"),
    url(r'^accountType/saveCreate$', views.accountTypeSaveCreate, name="accountTypeSaveCreate"),
    url(r'^accountType/read/(?P<id>[0-9]+)$', views.accountTypeRead, name="accountTypeRead"),
    url(r'^accountType/update/(?P<id>[0-9]+)$', views.accountTypeUpdate, name="accountTypeUpdate"),
    url(r'^accountType/saveUpdate/(?P<id>[0-9]+)$', views.accountTypeSaveUpdate, name="accountTypeSaveUpdate"),
    url(r'^accountType/confirmDelete/(?P<id>[0-9]+)$', views.accountTypeConfirmDelete, name="accountTypeConfirmDelete"),
    url(r'^accountType/delete/(?P<id>[0-9]+)$', views.accountTypeDelete, name="accountTypeDelete"),

    # Account
    url(r'^account/create$', views.accountCreate, name="accountCreate"),
    url(r'^account/saveCreate$', views.accountSaveCreate, name="accountSaveCreate"),
    url(r'^account/read/(?P<id>[0-9]+)$', views.accountRead, name="accountRead"),
    url(r'^account/update/(?P<id>[0-9]+)$', views.accountUpdate, name="accountUpdate"),
    url(r'^account/saveUpdate/(?P<id>[0-9]+)$', views.accountSaveUpdate, name="accountSaveUpdate"),
    url(r'^account/confirmDelete/(?P<id>[0-9]+)$', views.accountConfirmDelete, name="accountConfirmDelete"),
    url(r'^account/delete/(?P<id>[0-9]+)$', views.accountDelete, name="accountDelete"),

    # Transaction
    url(r'^transaction/create$', views.transactionCreate, name="transactionCreate"),
    url(r'^transaction/saveCreate$', views.transactionSaveCreate, name="transactionSaveCreate"),
    url(r'^transaction/read/(?P<id>[0-9]+)$', views.transactionRead, name="transactionRead"),
    url(r'^transaction/update/(?P<id>[0-9]+)$', views.transactionUpdate, name="transactionUpdate"),
    url(r'^transaction/saveUpdate/(?P<id>[0-9]+)$', views.transactionSaveUpdate, name="transactionSaveUpdate"),
    url(r'^transaction/confirmDelete/(?P<id>[0-9]+)$', views.transactionConfirmDelete, name="transactionConfirmDelete"),
    url(r'^transaction/delete/(?P<id>[0-9]+)$', views.transactionDelete, name="transactionDelete"),

    url(r'^changeDates/$', views.changeDates, name="changeDates"),
    url(r'^presetDate/$', views.presetDate, name="presetDate"),

    url(r'^search/$', views.search, name="search"),
]

minialexie/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login

import sitewide.views

urlpatterns = [
    url(r'^$', sitewide.views.index),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('django.contrib.auth.urls')),
    url(r'^accounts/profile/$', sitewide.views.UserProfile.as_view()),
    url(r'^alexie/', include('alexie.urls')),
    url(r'^allcents/', include('benny.urls')),
]

alexie/forms.py
from datetime import date

from django import forms

from .models import AccountType, Account

class AccountTypeForm(forms.ModelForm):
    class Meta:
        model = AccountType
        fields = ['id', 'name', 'sign']

class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['id', 'account_type', 'name', 'budget']
        
class TransactionForm(forms.Form):
    # Verbose, first attempt. A ModelForm is more compact
    created = forms.DateField(initial=date.today)
    description = forms.CharField(max_length=200)
    amount = forms.CharField(max_length=32)
    # populate querysets in view because user is not known in advance
    debit = forms.ModelChoiceField(queryset=None)  
    credit = forms.ModelChoiceField(queryset=None)

alexie/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, redirect
from django.utils.http import is_safe_url

from .models import AccountType, Account, Transaction
from .forms import AccountTypeForm, AccountForm, TransactionForm
from .util import parse_from_date, parse_to_date, parse_amount, display_amount
    
def index(request):
    """
    Display all account balances in the selected time period
    """
    
    # check if user is logged in
    if not request.user.is_authenticated():
        return redirect('/auth/login/')
        
    from_date = parse_from_date(request)
    to_date = parse_to_date(request)
    
    account_types = AccountType.objects.filter(user=request.user).order_by('name')
    account_type_names = {}
    
    accounts = {}
    account_names = {}
    account_balances = {}
    
    for account_type in account_types:
        account_type_names[account_type.id] = account_type.name
        accounts[account_type.id] = Account.objects.filter(account_type=account_type.id).order_by('name')
        for account in accounts[account_type.id]:
            account_names[account.id] = account.name
            account_balances[account.id] = account.balance(from_date, to_date)
        
    return render(request, "alexie/index.html",
                  { 'account_type_names': account_type_names,
                    'accounts': sorted(accounts.items()),
                    'account_names': account_names,
                    'account_balances': account_balances })

# For every model, there are eight functions

#               AccountType   Account    Transaction
#        create     done       done         done
#    saveCreate     done       done         done
#          read               sketch
#        update  needs link                 done
#    saveUpdate     done                    done
# confirmDelete                             done
#        delete  copy other  copy other     done
#    bulkDelete      not available       via checkboxes

# AccountType

def accountTypeCreate(request):
    form = AccountTypeForm()
    return render(request, 'alexie/accountTypeCreate.html', { 'form': form })
    
def accountTypeSaveCreate(request):
    # check for POST data to save, redirect to Create in any case
    if request.method == "POST":
        form = AccountTypeForm(request.POST)
        
        if form.is_valid():
            accountType = AccountType()
            accountType.user = request.user
            accountType.name = form.cleaned_data['name']
            # prevent invalid input: nonzero and greater than or less than +/-1
            if form.cleaned_data['sign'] == 0:
                accountType.sign = 1
            else:
                accountType.sign = round(form.cleaned_data['sign'] / abs(form.cleaned_data['sign']))
            accountType.save()
            
    return HttpResponseRedirect(reverse('alexie:accountTypeCreate'))
    
def accountTypeRead(request, pk):
    pass
    
def accountTypeUpdate(request, pk):
    accountType = AccountType.objects.get(user=request.user, pk=pk)
    form = AccountTypeForm(instance=accountType)
    return render(request, 'alexie/accountTypeUpdate.html', { 'form': form, 'id': pk })

def accountTypeSaveUpdate(request, pk):
    if request.method == "POST":
        form = AccountTypeForm(request.POST)
        
        if form.is_valid():
            accountType = AccountType.objects.get(user=request.user, pk=pk)
            accountType.name = form.cleaned_data['name']
            accountType.sign = round(form.cleaned_data['sign'] / abs(form.cleaned_data['sign']))
            accountType.save()
            
    return HttpResponseRedirect(reverse('alexie:accountTypeCreate'))

def accountTypeConfirmDelete(request, pk):
    pass
    
def accountTypeDelete(request, pk):
    # Copy code in transactionDelete
    accountType = AccountType.objects.get(user=request.user, pk=pk)
    accountType.delete()
    return HttpResponseRedirect(reverse('alexie:index'))


# Account

def accountCreate(request):
    form = AccountForm()
    # Show only user's account types
    form.fields['account_type'].queryset = AccountType.objects.filter(user=request.user)
    return render(request, 'alexie/accountCreate.html', { 'form': form })

def accountSaveCreate(request):
    if request.method == "POST":
        form = AccountForm(request.POST)

        if form.is_valid():
            account_type = AccountType.objects.get(user=request.user, pk=form.cleaned_data['account_type'].id)
            account = Account()
            account.user = request.user
            account.account_type = account_type
            account.name = form.cleaned_data['name']
            account.budget = form.cleaned_data['budget']
            account.save()
    return HttpResponseRedirect(reverse('alexie:accountCreate'))

def accountRead(request, pk):
    from_date = parse_from_date(request)
    to_date = parse_to_date(request)
    
    account = Account.objects.get(user=request.user, pk=pk)
    transactions = Transaction.objects.filter(
        debit=account,
        created__gte=from_date,
        created__lte=to_date) | Transaction.objects.filter(
        credit=account,
        created__gte=from_date,
        created__lte=to_date)
            
    return render(request, "alexie/accountRead.html",
                  { 'id': pk,
                    'account': account,
                    'transactions': transactions,
                    'prevUrl': reverse('alexie:accountRead', kwargs={ 'pk': pk }), })

def accountUpdate(request, pk):
    pass

def accountSaveUpdate(request, pk):
    pass

def accountConfirmDelete(request, pk):
    pass
    
def accountDelete(request, pk):
    account = Account.objects.get(user=request.user, pk=pk)
    account.delete()
    return HttpResponseRedirect(reverse('alexie:index'))
    
# Transaction

def transactionCreate(request):
    form = TransactionForm()
    accounts = Account.objects.filter(user=request.user).order_by('name')
    form.fields['debit'].queryset = accounts
    form.fields['credit'].queryset = accounts

    newestTransactions = Transaction.objects.filter(user=request.user).order_by('-created')[:25]
    return render(request, 'alexie/transactionCreate.html',
                  { 'form': form,
                    'newestTransactions': newestTransactions,
                    'prevUrl': reverse('alexie:transactionCreate'), })

def transactionSaveCreate(request):
    if request.method == "POST":
        form = TransactionForm(request.POST)
        form.fields['debit'].queryset = Account.objects.filter(user=request.user, pk=request.POST['debit'])
        form.fields['credit'].queryset = Account.objects.filter(user=request.user, pk=request.POST['credit'])

        if form.is_valid():
            transaction = Transaction()
            transaction.user = request.user
            transaction.description = form.cleaned_data['description']
            transaction.amount = parse_amount(form.cleaned_data['amount'])
            transaction.debit = form.cleaned_data['debit']
            transaction.credit = form.cleaned_data['credit']
            transaction.created = form.cleaned_data['created']
            transaction.save()
    return HttpResponseRedirect(reverse('alexie:transactionCreate'))
    
def transactionRead(request, pk):
    # share template with transactionConfirmDelete
    pass

def transactionUpdate(request, pk):
    transaction = Transaction.objects.get(user=request.user, pk=pk)
    try:
        debit_id = transaction.debit.id
    except AttributeError:
        # will occur if Transaction belonged to a deleted account
        debit_id = ""

    try:
        credit_id = transaction.credit.id
    except AttributeError:
        credit_id = ""
        
    form = TransactionForm({ 'created': transaction.created,
                             'description': transaction.description,
                             'amount': display_amount(transaction.amount),
                             'debit': debit_id,
                             'credit': credit_id, })
    form.fields['debit'].queryset = Account.objects.filter(user=request.user)
    form.fields['credit'].queryset = Account.objects.filter(user=request.user)
    return render(request, 'alexie/transactionUpdate.html', { 'form': form, 'id': pk })

def transactionSaveUpdate(request, pk):
    if request.method == "POST":
        form = TransactionForm(request.POST)
        form.fields['debit'].queryset = Account.objects.filter(user=request.user)
        form.fields['credit'].queryset = Account.objects.filter(user=request.user)
        
        if form.is_valid():
            transaction = Transaction.objects.get(user=request.user, pk=pk)
            transaction.description = form.cleaned_data['description']
            transaction.amount = parse_amount(form.cleaned_data['amount'])
            transaction.debit = form.cleaned_data['debit']
            transaction.credit = form.cleaned_data['credit']
            transaction.created = form.cleaned_data['created']
            transaction.save()
    return HttpResponseRedirect(reverse('alexie:transactionCreate'))

def transactionConfirmDelete(request, pk):
    # share detail template with transactionRead
    transaction = Transaction.objects.get(user=request.user, pk=pk)
    prevUrl = request.GET.get('prev', reverse('alexie:index'))
    nextUrl = reverse('alexie:transactionDelete', kwargs={ 'pk': pk }) + "?next=" + prevUrl
    if not is_safe_url(prevUrl):
        prev = reverse('alexie:index')
    return render(request, 'alexie/transactionConfirmDelete.html',
                  { 'transaction': transaction,
                    'prevUrl': prevUrl,
                    'nextUrl': nextUrl, })
    
def transactionDelete(request, pk):
    # http://stackoverflow.com/questions/35894990/django-how-to-return-to-previous-url
    next = request.GET.get('next', reverse('alexie:index'))

alexie/templates/alexie/account.html
<body>
    <a href="/alexie/">ALEXIE home</a>
    
    <pre>
    {{ id }}
    {{ account.name }}

    {% for transaction in transactions %}
         {{ transaction.created }}   {{ transaction.description }} {{ transaction.amount }} {{ transaction.debit }} {{ transaction.credit }}
    {% endfor %}
    </pre>
</body>

alexie/templates/alexie/accountCreate.html
{% extends "alexie/base.html" %}

{% block title %}Create Account{% endblock %}

{% block content %}
<form action="{% url 'alexie:accountSaveCreate' %}" method="POST">
    {% csrf_token %}
    {{ form.as_ul }}
    <input type="submit">
</form>
{% endblock %}

alexie/templates/alexie/accountRead.html
{% extends "alexie/base.html" %}

{% block title %}View Account{% endblock %}

{% block content %}
    {{ id }}
    {{ account.name }}

    {% for transaction in transactions %}

{% include 'alexie/transactionSingleLine.html' %}

    {% endfor %}

{% endblock %}

alexie/templates/alexie/accountTypeCreate.html
{% extends "alexie/base.html" %}

{% block title %}Create Account Type{% endblock %}

{% block content %}
<form action="{% url 'alexie:accountTypeSave' %}" method="POST">
    {% csrf_token %}
    <table>
        <tr>
            <td>Name:</td>
            <td>{{ form.name }}</td>
        </tr>
        <tr>
            <td>Sign (+/-1):</td>
            <td>{{ form.sign }}</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td><input type="submit" value="Submit transaction"></td>
        </tr>
    </table>

</form>

<pre>
{% for accounttype in accounttypes %}
{{ accounttype.name }} ({{ accounttype.sign }})
{% endfor %}
</pre>
{% endblock %}

alexie/templates/alexie/accountTypeUpdate.html
{% extends "alexie/base.html" %}

{% block title %}Update Account Type{% endblock %}

{% block content %}
<form action="{% url 'alexie:accountTypeSaveUpdate' id %}" method="POST">
    {{ form }}
    {% csrf_token %}
    <table>
        <tr>
            <td>Name:</td>
            <td>{{ form.name }}</td>
        </tr>
        <tr>
            <td>Sign (+/-1):</td>
            <td>{{ form.sign }}</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td><input type="submit" value="Submit transaction"></td>
        </tr>
    </table>

</form>

<pre>
{% for accounttype in accounttypes %}
{{ accounttype.name }} ({{ accounttype.sign }})
{% endfor %}
</pre>
{% endblock %}

alexie/templates/alexie/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Mini Alexie {% block title %}{% endblock %}</title>
        <!-- In Benny Static URL is used -->
        <!-- <link rel="stylesheet" href=""> -->
        <style>
         .indexAccountType {
             float: left;
             padding: 25px;
         }
             
        </style>
    </head>
    <body>
        <div id="header">
            {% include "alexie/header.html" %}
        </div>
        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

alexie/templates/alexie/header.html
({{ request.user }})
<a href="{% url 'alexie:index' %}">Home</a>
|
<a href="{% url 'alexie:accountTypeCreate' %}">Create Account Type</a>
|
<a href="{% url 'alexie:accountCreate' %}">Create Account</a>
|
<a href="{% url 'alexie:transactionCreate' %}">Create Transaction</a>

<br><br>

alexie/templates/alexie/index.html
{% extends "alexie/base.html" %}
{% load alexie_filters %}

{% block title %}Homepage{% endblock %}

{% block content %}

<!-- https://docs.djangoproject.com/en/1.10/ref/templates/builtins/ -->
<!-- Access keys and values of dictionary 'accounts' -->
<!-- Use accounts only because we call items() in view, inside sorted() -->
{% for account_type_id, accounts in accounts %}
<div class="indexAccountType">
    <i>{{ account_type_names|get_item:account_type_id }}</i>
    ({{ account_type_id }})
    <table>
        {% for account in accounts %}
        <tr>
            <td><a href="{% url 'alexie:accountRead' account.id %}">{{ account_names|get_item:account.id }}</a></td>
            <td style="padding-left: 15px; text-align: right;">{{ account_balances|get_item:account.id }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endfor %}

</pre>
{% endblock %}

alexie/templates/alexie/transactionConfirmDelete.html
{% extends "alexie/base.html" %}

{% block title %}Confirm Delete Transaction{% endblock %}

{% block content %}

About to delete transaction:

{% include 'alexie/transactionDetail.html' %}

<pre>
Are you sure?

    <a href="{{ nextUrl }}">Yes</a>

    <a href="{{ prevUrl }}">No</a>
</pre>

{% endblock %}

alexie/templates/alexie/transactionCreate.html
{% extends "alexie/base.html" %}

{% block title %}Create Transaction{% endblock %}

{% block content %}
<form action="{% url 'alexie:transactionSaveCreate' %}" method="POST">
    {% csrf_token %}
    <table>
        <tr>
            <td>Date:</td>
            <td>{{ form.created }}</td>
        </tr>
        <tr>
            <td>Description:</td>
            <td>{{ form.description }}</td>
        </tr>
        <tr>
            <td>Amount</td>
            <td>{{ form.amount }}</td>
        </tr>
        <tr>
            <td>Debit</td>
            <td>{{ form.debit }}</td>
        </tr>
        <tr>            
            <td>Credit</td>
            <td>{{ form.credit }}</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td><input type="submit" value="Submit transaction"></td>
        </tr>
    </table>

</form>

<!-- Newest 25 transactions -->
{% for transaction in newestTransactions %}
{% include 'alexie/transactionSingleLine.html' %}
{% endfor %}

<script>
    document.getElementById("id_description").focus();
</script>

{% endblock %}

alexie/templates/alexie/transactionDetail.html
Transaction Detail

<pre>
{{ transaction.created }}
{{ transaction.description }}
{{ transaction.amount }}
{{ transaction.debit }}
{{ transaction.credit }}
</pre>

alexie/templates/alexie/transactionSingleLine.html
<p>
    <a href="{% url 'alexie:transactionConfirmDelete' transaction.id %}?prev={{ prevUrl }}">(delete)</a>
    <a href="{% url 'alexie:transactionUpdate' transaction.id %}">{{ transaction }}</a>
</p>

alexie/templates/alexie/transactionUpdate.html
{% extends "alexie/base.html" %}

{% block title %}Update Transaction{% endblock %}

{% block content %}
<form action="{% url 'alexie:transactionSaveUpdate' id %}" method="POST">
    {% csrf_token %}
    <table>
        <tr>
            <td>Date:</td>
            <td>{{ form.created }}</td>
        </tr>
        <tr>
            <td>Description:</td>
            <td>{{ form.description }}</td>
        </tr>
        <tr>
            <td>Amount</td>
            <td>{{ form.amount }}</td>
        </tr>
        <tr>
            <td>Debit</td>
            <td>{{ form.debit }}</td>
        </tr>
        <tr>            
            <td>Credit</td>
            <td>{{ form.credit }}</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td><input type="submit" value="Submit transaction"></td>
        </tr>
    </table>

</form>

<!-- Newest 25 transactions -->
<pre>
{% for transaction in newestTransactions %}
{{ transaction }}
{% endfor %}
</pre>
{% endblock %}