benny/urls.py
from django.conf.urls import url

from . import views

app_name = "benny"

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # For every model

    # create
    # saveCreate  # avoid "confirm form resubmission" on browser reload
    # read
    # update
    # saveUpdate
    # confirmDelete
    # delete
    
    # AccountType

    url(r'^accountType/create$', views.accountTypeCreate, name="accountTypeCreate"),
    url(r'^accountType/saveCreate$', views.accountTypeSaveCreate, name="accountTypeSaveCreate"),
    url(r'^accountType/read/(?P<id>[0-9]+)$', views.accountTypeRead, name="accountTypeRead"),
    url(r'^accountType/update/(?P<id>[0-9]+)$', views.accountTypeUpdate, name="accountTypeUpdate"),
    url(r'^accountType/saveUpdate/(?P<id>[0-9]+)$', views.accountTypeSaveUpdate, name="accountTypeSaveUpdate"),
    url(r'^accountType/confirmDelete/(?P<id>[0-9]+)$', views.accountTypeConfirmDelete, name="accountTypeConfirmDelete"),
    url(r'^accountType/delete/(?P<id>[0-9]+)$', views.accountTypeDelete, name="accountTypeDelete"),

    # Account
    url(r'^account/create$', views.accountCreate, name="accountCreate"),
    url(r'^account/saveCreate$', views.accountSaveCreate, name="accountSaveCreate"),
    url(r'^account/read/(?P<id>[0-9]+)$', views.accountRead, name="accountRead"),
    url(r'^account/update/(?P<id>[0-9]+)$', views.accountUpdate, name="accountUpdate"),
    url(r'^account/saveUpdate/(?P<id>[0-9]+)$', views.accountSaveUpdate, name="accountSaveUpdate"),
    url(r'^account/confirmDelete/(?P<id>[0-9]+)$', views.accountConfirmDelete, name="accountConfirmDelete"),
    url(r'^account/delete/(?P<id>[0-9]+)$', views.accountDelete, name="accountDelete"),

    # Transaction
    url(r'^transaction/create$', views.transactionCreate, name="transactionCreate"),
    url(r'^transaction/saveCreate$', views.transactionSaveCreate, name="transactionSaveCreate"),
    url(r'^transaction/read/(?P<id>[0-9]+)$', views.transactionRead, name="transactionRead"),
    url(r'^transaction/update/(?P<id>[0-9]+)$', views.transactionUpdate, name="transactionUpdate"),
    url(r'^transaction/saveUpdate/(?P<id>[0-9]+)$', views.transactionSaveUpdate, name="transactionSaveUpdate"),
    url(r'^transaction/confirmDelete/(?P<id>[0-9]+)$', views.transactionConfirmDelete, name="transactionConfirmDelete"),
    url(r'^transaction/delete/(?P<id>[0-9]+)$', views.transactionDelete, name="transactionDelete"),

    url(r'^changeDates/$', views.changeDates, name="changeDates"),
    url(r'^presetDate/$', views.presetDate, name="presetDate"),

    url(r'^search/$', views.search, name="search"),
]

minialexie/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login

import sitewide.views

urlpatterns = [
    url(r'^$', sitewide.views.index),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('django.contrib.auth.urls')),
    url(r'^accounts/profile/$', sitewide.views.UserProfile.as_view()),
    url(r'^alexie/', include('alexie.urls')),
    url(r'^allcents/', include('benny.urls')),
]

alexie/models.py
from datetime import date

from django.db import models
from django.contrib.auth.models import User

# AccountType

# Account

# Transaction

class AccountType(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='AccountTypeUser')
    name = models.CharField(max_length=100)
    sign = models.IntegerField()

    def __str__(self):
        return "%s (%s)" % (self.name, self.sign)

# repeat User ForeignKey for convenience, such as looking up all entries, or cascading delete

class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='AccountUser')
    account_type = models.ForeignKey(AccountType, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100)
    budget = models.IntegerField(default=0)

    def balance(self, from_date=date(1900, 1, 1), to_date=date(2100, 1, 1)):
        total = 0
        debit_transactions = self.debit_transactions.filter(created__gte=from_date, created__lte=to_date)
        credit_transactions = self.credit_transactions.filter(created__gte=from_date, created__lte=to_date)

        for debit in debit_transactions:
            total += self.account_type.sign * debit.amount

        for credit in credit_transactions:
            total -= self.account_type.sign * credit.amount

        return total

    def __str__(self):
        return "%s" % self.name

class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='TransactionUser')
    description = models.CharField(max_length=200)
    amount = models.IntegerField()
    debit = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True, related_name="debit_transactions")
    credit = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True, related_name="credit_transactions")
    created = models.DateField("Creation date of transaction", default=date.today)

    def __str__(self):
        return "%s %s %s %s/%s" % (self.created, self.description, self.amount, self.debit, self.credit)
        

sitewide/models.py
from django.db import models

# Create your models here.

benny/forms.py
from django import forms

from .models import AccountType, Account, Transaction

class AccountTypeForm(forms.ModelForm):
    class Meta:
        model = AccountType
        fields = ['name', 'sign']

class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['accountType', 'name', 'budget']

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['description', 'amount', 'debit', 'credit', 'date']
        widgets = {
            'description': forms.TextInput(attrs={'size': 60}),
        }

benny/views.py
from datetime import date, datetime
from calendar import monthrange
from math import ceil
from decimal import Decimal

from django.urls import reverse
from django.shortcuts import render, redirect
from django.utils.http import is_safe_url

from .models import AccountType, Account, Transaction
from .forms import AccountTypeForm, AccountForm, TransactionForm
from .util import parseDate, parseFromDate, parseToDate, displayDate
from .util import DEFAULT_FROM_DATE, DEFAULT_TO_DATE
from .util import parseAccountTypeSign, nextOrderIndex

def index(request):
    """
    Display all account balances in the selected time period.
    """
    if not request.user.is_authenticated():
        return redirect(reverse('login'))

    accountTypes = AccountType.objects.filter(user=request.user).order_by('order', 'name')

    fromDate = parseFromDate(request)
    toDate = parseToDate(request)

    for accountType in accountTypes:
        # retrieve balances here, using the parsed from and to dates
        accountType.accountSummaries = accountType.summarizeAccounts(fromDate, toDate)

        # compute total for accountType
        if len(accountType.accountSummaries) == 0:
            accountType.total = Decimal("0.00")
        else:
            accountType.total = sum([account['datesBalance'] for account in accountType.accountSummaries])

    return render(request, 'benny/index.html',
                  {'accountTypes': accountTypes,
                   'fromDate': displayDate(fromDate),
                   'toDate': displayDate(toDate)})

# For every model, there are up to eight functions
#
#               AccountType   Account    Transaction
#        create     done       done         done
#    saveCreate     done       done         done
#          read     done       done         done
#        update     done       done         done
#    saveUpdate     done       done         done
# confirmDelete     done       done         done
#        delete     done       done         done
# confirmBulkDl    ( not available ) 
#    bulkDelete    ( not available )    

###############
# AccountType #
###############

def accountTypeCreate(request):
    form = AccountTypeForm()
    return render(request, 'benny/accountTypeCreate.html',
                  {'form': form})

def accountTypeSaveCreate(request):
    if request.method == "POST":
        form = AccountTypeForm(request.POST)
        if form.is_valid():
            accountType = AccountType()
            accountType.user = request.user
            accountType.name = form.cleaned_data['name']
            # set new accountType's order to last place
            accountType.order = nextOrderIndex(AccountType, request.user)
            accountType.sign = parseAccountTypeSign(form.cleaned_data['sign'])
            accountType.save()
            # return redirect(reverse('benny:accountTypeRead', kwargs={'id': accountType.id}))
            return redirect(reverse('benny:index'))
    # if this point is reached, something must have gone wrong
    return redirect(reverse('benny:index'))

def accountTypeRead(request, id):
    # https://docs.djangoproject.com/en/1.10/intro/tutorial04/
    # in 'objects.get', use pk=id as search criteria
    accountType = AccountType.objects.get(user=request.user, pk=id)
    
    accounts = Account.objects.filter(user=request.user, accountType=accountType).order_by('name')  # order alphabetically
    accountSummaries = accountType.summarizeAccounts(parseFromDate(request), parseToDate(request))
    return render(request, 'benny/accountTypeRead.html',
                  {'accountType': accountType,
                   'accountSummaries': accountSummaries})

def accountTypeUpdate(request, id):
    accountType = AccountType.objects.get(user=request.user, pk=id)
    form = AccountTypeForm(instance=accountType)
    return render(request, 'benny/accountTypeUpdate.html', {'form': form, 'id': id})

def accountTypeSaveUpdate(request, id):
    if request.method == "POST":
        form = AccountTypeForm(request.POST)
        if form.is_valid():
            accountType = AccountType.objects.get(user=request.user, pk=id)
            accountType.name = form.cleaned_data['name']
            accountType.sign = parseAccountTypeSign(form.cleaned_data['sign'])
            accountType.save()
    # return redirect(reverse('benny:accountTypeRead', kwargs={'id': id}))
    return redirect(reverse('benny:index'))

def accountTypeConfirmDelete(request, id):
    accountType = AccountType.objects.get(user=request.user, pk=id)
    # if the GET parameter 'prev' is not set, send back to accountTypeRead
    prevUrl = request.GET.get('prev', reverse('benny:index'))
    nextUrl = reverse('benny:accountTypeDelete', kwargs={'id': id}) + "?next=" + prevUrl
    if not is_safe_url(prevUrl):
        prevUrl = reverse('benny:index')
    return render(request, 'benny/accountTypeConfirmDelete.html',
                  {'accountType': accountType,
                   'prevUrl': prevUrl,
                   'nextUrl': nextUrl})

def accountTypeDelete(request, id):
    accountType = AccountType.objects.get(user=request.user, pk=id)
    accountType.delete()
    return redirect(reverse('benny:index'))

###########
# Account #
###########

def accountCreate(request):
    # try auto-selecting account type
    accountTypeId = request.GET.get('accountType', "")

    form = AccountForm(initial={'accountType': accountTypeId})
    # Show only user's account types
    form.fields['accountType'].queryset = AccountType.objects.filter(user=request.user).order_by('order', 'name')  # order by index

    return render(request, 'benny/accountCreate.html', {'form': form})

def accountSaveCreate(request):
    if request.method == "POST":
        form = AccountForm(request.POST)
        if form.is_valid():
            # restrict to object belonging to user
            accountType = AccountType.objects.get(user=request.user, pk=form.cleaned_data['accountType'].id)
            
            account = Account()
            account.user = request.user
            account.accountType = accountType
            account.name = form.cleaned_data['name']
            account.budget = form.cleaned_data['budget']
            account.order = nextOrderIndex(Account, request.user)
            account.save()
            # return redirect(reverse('benny:accountTypeRead', kwargs={'id': accountType.id}))
            return redirect(reverse('benny:index'))
    # if this point is reached, something must have gone wrong
    return redirect(reverse('benny:index'))

def accountRead(request, id):
    account = Account.objects.get(user=request.user, pk=id)
    from_date = parseFromDate(request)
    to_date = parseToDate(request)
    
    transactions = Transaction.objects.filter(
        debit=account,
        date__gte=from_date,
        date__lte=to_date) | Transaction.objects.filter(
            credit=account,
            date__gte=from_date,
            date__lte=to_date)
    transactions = transactions.order_by('-date')

    return render(request, 'benny/accountRead.html',
                  {'account': account,
                   'accountBalance': account.balance(from_date, to_date),
                   'transactions': transactions})

def accountUpdate(request, id):
    account = Account.objects.get(user=request.user, pk=id)
    form = AccountForm(instance=account)
    form.fields['accountType'].queryset = AccountType.objects.filter(user=request.user)
    return render(request, 'benny/accountUpdate.html', {'id': id, 'form': form})

def accountSaveUpdate(request, id):
    if request.method == "POST":
        form = AccountForm(request.POST)
        if form.is_valid():
            accountType = AccountType.objects.get(user=request.user, pk=form.cleaned_data['accountType'].id)
            
            account = Account.objects.get(user=request.user, pk=id)
            account.accountType = accountType
            account.name = form.cleaned_data['name']
            account.budget = form.cleaned_data['budget']
            account.save()
    return redirect(reverse('benny:accountRead', kwargs={'id': id}))

def accountConfirmDelete(request, id):
    account = Account.objects.get(user=request.user, pk=id)
    prevUrl = request.GET.get('prev', reverse('benny:accountRead', kwargs={'id': id}))
    nextUrl = reverse('benny:accountDelete', kwargs={'id': id}) + "?next=" + prevUrl
    if not is_safe_url(prevUrl):
        prevUrl = reverse('benny:accountRead', kwargs={'id': id})
    return render(request, 'benny/accountConfirmDelete.html',
                  {'account': account,
                   'prevUrl': prevUrl,
                   'nextUrl': nextUrl})

def accountDelete(request, id):
    account = Account.objects.get(user=request.user, pk=id)
    account.delete()
    return redirect(reverse('benny:index'))

###############
# Transaction #
###############

def transactionCreate(request):
    form = TransactionForm()
    userAccounts = Account.objects.filter(user=request.user).order_by('name')
    form.fields['debit'].queryset = userAccounts
    form.fields['credit'].queryset = userAccounts
    return render(request, 'benny/transactionCreate.html', {'form': form})

def transactionSaveCreate(request):
    if request.method == "POST":
        form = TransactionForm(request.POST)
        if form.is_valid():
            debit = Account.objects.get(user=request.user, pk=form.cleaned_data['debit'].id)
            credit = Account.objects.get(user=request.user, pk=form.cleaned_data['credit'].id)

            transaction = Transaction()
            transaction.user = request.user
            transaction.description = form.cleaned_data['description']
            transaction.amount = form.cleaned_data['amount']
            transaction.debit = debit
            transaction.credit = credit
            transaction.date = form.cleaned_data['date']
            transaction.save()
            return redirect(reverse('benny:transactionRead', kwargs={'id': transaction.id}))

benny/templates/benny/accountConfirmDelete.html
{% extends "benny/base.html" %}
{% block title %}Account - Confirm Delete{% endblock %}

{% block content %}
<h1>Delete {{ account.name }}?</h1>

{% include 'benny/areYouSure.html' %}
{% endblock %}

benny/templates/benny/accountCreate.html
{% extends "benny/base.html" %}
{% block title %}Account - Create{% endblock %}

{% block content %}
<h1>New account</h1>

<form action="{% url 'benny:accountSaveCreate' %}" method="POST">
    {% csrf_token %}
    {% include 'benny/modelForm.html' %}
</form>
{% endblock %}

benny/templates/benny/accountRead.html
{% extends "benny/base.html" %}
{% load humanize %}
{% block title %}Account - Read{% endblock %}

{% block content %}
<div class="accountTypeBlock">
    <span class="accountName">{{ account.name }}</span>
    &nbsp;
    <a href="{% url 'benny:accountUpdate' account.id %}" class="small">edit</a> | <a href="{% url 'benny:accountConfirmDelete' account.id %}" class="small">delete</a>

    <br><br>
    <table class="transactionSummariesTable">
        <tr>
            <th>&nbsp;</th>
            <th>Date</th>
            <th>Description</th>
            <th class="amount">Amount</th>
            <th>Debit</th>
            <th>Credit</th>
        </tr>
        {% for transaction in transactions %}
        {% include 'benny/transactionSummaryLine.html' %}
        {% endfor %}
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td class="total">Total</td>
            <td class="amount total">{{ accountBalance|intcomma }}</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
    </table>
</div>

{% endblock %}

benny/templates/benny/accountTypeConfirmDelete.html
{% extends "benny/base.html" %}
{% block title %}Account Type - Confirm Delete{% endblock %}

{% block content %}
<h1>Delete {{ accountType.name }}?</h1>

<p>
Are you sure?
</p>

<p><a href="{{ nextUrl }}">Yes</a></p>

<p><a href="{{ prevUrl }}">No, go back</a></p>
{% endblock %}

benny/templates/benny/accountTypeCreate.html
{% extends "benny/base.html" %}
{% block title %}Account Type - Create{% endblock %}

{% block content %}
<h1>New account type</h1>

<form action="{% url 'benny:accountTypeSaveCreate' %}" method="POST">
    {% csrf_token %}
    {% include 'benny/modelForm.html' %}
</form>
{% endblock %}

benny/templates/benny/accountUpdate.html
{% extends "benny/base.html" %}
{% block title %}Account - Update{% endblock %}

{% block content %}
<h1>Edit account</h1>

<form action="{% url 'benny:accountSaveUpdate' id %}" method="POST">
    {% csrf_token %}
    {% include 'benny/modelForm.html' %}
</form>

{% endblock %}

benny/templates/benny/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>Benny {% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'benny/style.css' %}">
        <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </head>

    <body>
        {% include "benny/header.html" %}
        <div id="content">
            {% block content %}{% endblock %}
        </div>

        <div id="footer">
            {% block footer %}{% endblock %}
        </div>

        <div id="spacer"></div>
    </body>
</html>

benny/templates/benny/header.html
<nav class="navbar navbar-default"> <!-- navbar-fixed-top"> -->
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li><a href="{% url 'benny:index' %}" class="accountName">All Cents</a></li>
            
            <li class="dropdown"> <!-- user -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user gi-default-size"></span></a>
                <ul class="dropdown-menu">
                    <li class="dropdown-header">{{ request.user }}</li>
                    <li><a href="{% url 'logout' %}?next={% url 'benny:index' %}">Logout</a></li>
                </ul>
            </li> <!-- user dropdown -->

            <li><a href="{% url 'benny:index' %}"><span class="glyphicon glyphicon-list-alt gi-default-size"></span></a></li>  <!-- list of all accounts -->

            <li class="dropdown"> <!-- new item -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-plus gi-default-size"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'benny:accountTypeCreate' %}">New account type</a></li>
                    <li><a href="{% url 'benny:accountCreate' %}">New account</a></li>
                    <li><a href="{% url 'benny:transactionCreate' %}">New transaction</a></li>
                </ul>
            </li> <!-- new item dropdown -->

            <li class="dropdown"> <!-- calendar -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-calendar gi-default-size"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'benny:presetDate' %}?choice=today&amp;prevUrl={{ request.path }}">Today</a></li>
                    <li><a href="{% url 'benny:presetDate' %}?choice=month&amp;prevUrl={{ request.path }}">This month</a></li>
                    <li><a href="{% url 'benny:presetDate' %}?choice=year&amp;prevUrl={{ request.path }}">This year</a></li>
                    <li><a href="{% url 'benny:presetDate' %}?choice=all&amp;prevUrl={{ request.path }}">All dates</a></li>
                </ul>
            </li> <!-- calendar dropdown -->
            
        </ul> <!-- nav navbar-nav -->
     
        <form action="{% url 'benny:changeDates' %}" method="POST" class="navbar-form navbar-left small">
            {% csrf_token %}

            activity from
            &nbsp;
            <input type="text" name="from" size="10" value="{{ request.session.fromDate }}">

            to

            <input type="text" name="to" size="10" value="{{ request.session.toDate }}">

            <input type="hidden" name="prevUrl" value="{{ request.path }}">
            <input type="submit" value="change">            
        </form> <!-- changeDates -->

        <form action="{% url 'benny:search' %}" method="POST" class="navbar-form navbar-left small">
            {% csrf_token %}
            
            <span class="glyphicon glyphicon-search gi-default-size"></span>
            <input type="text" name="words" size="15">
            <input type="submit" value="search">
        </form>
    </div>
</nav>

benny/templates/benny/index.html
{% extends 'benny/base.html' %}
{% load humanize %}
{% block title %}Home{% endblock %}

{% block content %}

<!-- <div class="accountTypeRow"> -->

    {% for accountType in accountTypes %}
    <div class="accountTypeBlock">
        <!-- <a href="{% url 'benny:accountTypeRead' accountType.id %}"><span class="accountTypeName">{{ accountType.name }}</span></a> -->
        <span class="accountTypeName">{{ accountType.name }}</span>
        &nbsp;
        <a href="{% url 'benny:accountTypeUpdate' accountType.id %}" class="small">edit</a> |
        <a href="{% url 'benny:accountTypeConfirmDelete' accountType.id %}" class="small">delete</a>

        <!--
        <p>
            <a href="{% url 'benny:accountCreate' %}?accountType={{ accountType.id }}" class="small newItem"> + create new account</a>
        </p>
        -->

        <table class="accountSummariesTable">
            {% for account in accountType.accountSummaries %}
            {% include 'benny/accountSummaryLine.html' %}
            {% endfor %}
            <!-- account type total -->
            <tr>
                <td class="total">
                    Total
                </td>
                <td class="amount total">
                    {{ accountType.total|intcomma }}
                </td>
            </tr>
        </table>
    </div>
    {% endfor %}

    <!--
    <div class="accountTypeBlock">
        <a href="{% url 'benny:accountTypeCreate' %}" class="small newItem"> + create new account type</a>
    </div>
    -->

    <!-- </div> -->
{% endblock %}

benny/templates/benny/modelForm.html
<table class="modelTable">
    {{ form.as_table }}
    <tr>
        <td>&nbsp;</td>
        <td><input type="submit"></td>
    </tr>
</table>

benny/templates/benny/template.html
{% extends "benny/base.html" %}
{% block title %}{% endblock %}

{% block content %}

{% endblock %}

benny/templates/benny/transactionCreate.html
{% extends "benny/base.html" %}
{% block title %}Transaction - Create{% endblock %}

{% block content %}
<h1>New transaction</h1>

<form action="{% url 'benny:transactionSaveCreate' %}" method="POST">
    {% csrf_token %}
    {% include 'benny/modelForm.html' %}
</form>
{% endblock %}

benny/templates/benny/transactionSummaryLine.html
{% load humanize %}
<tr>
    <td>
    <a href="{% url 'benny:transactionUpdate' transaction.id %}">edit</a>
    |
    <a href="{% url 'benny:transactionConfirmDelete' transaction.id %}">delete</a>
    </td>
    <td>
        {{ transaction.date|date:"d/m/Y" }}
    </td>
    <td>
        {{ transaction.description }}
    </td>
    <td class="amount">
        {{ transaction.amount|intcomma }}
    </td>
    <td>
        {{ transaction.debit }}
    </td>
    <td>
        {{ transaction.credit }}
    </td>
</tr>

benny/templates/benny/transactionUpdate.html
{% extends "benny/base.html" %}
{% block title %}Transaction - Update{% endblock %}

{% block content %}
<h1>Transaction - Update</h1>

<form action="{% url 'benny:transactionSaveUpdate' id %}" method="POST">
    {% csrf_token %}
    {% include 'benny/modelForm.html' %}
</form>

{% endblock %}